---
# tasks file for act-topgen
- name: Create required output directories if not present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - "{{ output_folder }}"
  delegate_to: localhost
  run_once: true

- name: Include device structured configuration variables
  include_vars: "{{ filename }}"
  delegate_to: localhost
  vars:
    filename: "{{ structured_folder }}/{{ inventory_hostname }}.{{ avd_structured_config_file_format }}"
  tags:
    - always

- name: Build topology
  delegate_to: localhost
  run_once: true
  template:
    src: main.j2
    dest: "{{ output_folder }}/{{ output_filename }}"
    mode: 0664

#Clab
- name: Create required clab output directories if not present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - "{{ clab_output_folder }}"
  delegate_to: localhost
  run_once: true    

- name: Create required clab/config output directories if not present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - "{{ clab_output_folder }}/{{ clab_config_dir }}"
  delegate_to: localhost
  run_once: true   

- name: Build topology Clab
  delegate_to: localhost
  run_once: true
  template:
    src: clab-main.j2
    dest: "{{ clab_output_folder }}/{{ clab_output_filename }}"
    mode: 0664  

- name: Build basefile clab
  delegate_to: localhost
  template:
    src: clab-config-base.j2
    dest: "{{ clab_output_folder }}/{{ clab_config_dir }}/{{ inventory_hostname }}.cfg"
    mode: 0664  